/* Build the Kanban Manager canvas extension into one self-contained browser
   ESM file: the bundle carries the board, the stylesheet and the manager
   automation's python sources, because an extension is a single file.

   The stylesheet is NOT copied: it is read from ../../static/style.css so the
   standalone SPA stays the single source of truth for the design. Two
   transforms adapt it to living inside Canvas:

   1. Every selector is scoped under .vibe-ext, and the page-level selectors
      (:root, html, body, *) are rewritten onto that root, so the extension
      cannot restyle Canvas.
   2. rem lengths become calc(N * var(--vibe-rem)). The SPA sets
      html { font-size: 120% } to scale itself, which an extension must not do
      to the host page; --vibe-rem reproduces that scale locally instead.
*/

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import esbuild from "esbuild";
import postcss from "postcss";
import prefixer from "postcss-prefix-selector";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT_CLASS = ".vibe-ext";
const SOURCE_CSS = join(here, "..", "..", "static", "style.css");

/* The manager automation's python package. It is compiled into the bundle
   because "Start manager" uploads it from the browser, and the Canvas machine
   has no vibe-manager checkout to read it from. Same rule as the stylesheet:
   automation/ stays the single source of truth. */
const AUTOMATION_DIR = join(here, "..", "..", "automation");
const AUTOMATION_MODULES = ["main.py", "vibestore.py", "vibectl.py"];

// Selectors that target the page itself. Inside the extension they all mean
// "our root element" instead.
const PAGE_LEVEL = new Set([
  ":root",
  "html",
  "body",
  "html, body",
  "html,body",
]);

function scopeSelector(selector) {
  const trimmed = selector.trim();
  if (PAGE_LEVEL.has(trimmed)) return ROOT_CLASS;

  // html[data-theme="light"] -> .vibe-ext[data-theme="light"]  (the SPA's light
  // mode is a token override; we keep it on our own root so the toggle never
  // touches Canvas's <html>).
  if (trimmed.startsWith("html[")) {
    return ROOT_CLASS + trimmed.slice("html".length);
  }
  // html[data-theme="light"] .foo -> .vibe-ext[data-theme="light"] .foo
  if (trimmed.startsWith("html[data-theme")) {
    return ROOT_CLASS + trimmed.slice("html".length);
  }
  if (trimmed === "*") return `${ROOT_CLASS}, ${ROOT_CLASS} *`;
  return null; // fall through to the default prefixer behaviour
}

function remToScaled(css) {
  // 0.9375rem -> calc(0.9375 * var(--vibe-rem)). Skip 0rem and anything already
  // inside a var() fallback chain we generated.
  return css.replace(/(-?\d*\.?\d+)rem\b/g, (match, value) => {
    const n = Number(value);
    if (!Number.isFinite(n) || n === 0) return match;
    return `calc(${value} * var(--vibe-rem))`;
  });
}

async function buildCss() {
  const raw = readFileSync(SOURCE_CSS, "utf8");
  const result = await postcss([
    prefixer({
      prefix: ROOT_CLASS,
      transform(prefix, selector, prefixedSelector) {
        return scopeSelector(selector) ?? prefixedSelector;
      },
    }),
  ]).process(raw, { from: SOURCE_CSS });

  // --vibe-rem reproduces the SPA's html { font-size: 120% } locally. Change
  // this one value to rescale the whole board inside Canvas.
  const scale = `${ROOT_CLASS} { --vibe-rem: 1.2rem; }\n`;
  // setup.css is extension-only and already written scoped, so it bypasses the
  // prefixer but still gets the rem rescale.
  const setup = readFileSync(join(here, "src", "setup.css"), "utf8");
  return scale + remToScaled(result.css) + remToScaled(setup);
}

function readAutomation() {
  return Object.fromEntries(
    AUTOMATION_MODULES.map((name) => [name, readFileSync(join(AUTOMATION_DIR, name), "utf8")]),
  );
}

const css = await buildCss();
const automation = readAutomation();
mkdirSync(join(here, "dist"), { recursive: true });

await esbuild.build({
  entryPoints: [join(here, "src", "extension.js")],
  outfile: join(here, "dist", "extension.js"),
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  legalComments: "none",
  define: {
    __VIBE_CSS__: JSON.stringify(css),
    __VIBE_AUTOMATION__: JSON.stringify(automation),
  },
});

const out = readFileSync(join(here, "dist", "extension.js"), "utf8");
writeFileSync(
  join(here, "dist", "extension.js"),
  `/* Generated by extensions/kanban-manager/build.mjs - do not edit. */\n${out}`,
);
console.log(`built dist/extension.js (${(out.length / 1024).toFixed(1)} KB)`);
